[project]
name = "quickfin"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "dash>=2.17",
  "plotly>=5.23",
  "pandas>=2.2",
  "requests>=2.32",
  "beautifulsoup4>=4.12",
  "numpy>=1.26",
  "sqlalchemy>=2.0",
  "psycopg2-binary>=2.9"
]

[tool.pytest.ini_options]
pythonpath = ["."]
