name: e2e

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Start app
        env:
          PORT: 8050
        run: |
          python -m app.main & echo $! > app.pid
          n=0
          until curl -sSf http://localhost:8050 >/dev/null; do
            n=$((n+1)); [ $n -gt 60 ] && exit 1; sleep 1
          done

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Playwright deps
        run: |
          pnpm add -D @playwright/test
          npx playwright install --with-deps

      - name: Run Playwright
        run: npx playwright test
        env:
          BASE_URL: http://localhost:8050

      - name: Run unit tests
        run: pytest -q

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Stop app
        if: always()
        run: kill $(cat app.pid) || true
